version: '3'

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/srv
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - sf_network
    restart: always

networks:
  sf_network:
    external: true